# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14fc6112dd3bce50b44007d65b07666c6a98c974ee466b0b472b383b8d9309f0db661856eb43077f9d4fcd9a39c8e63217c73f486d2fdbf2be0efe548f6a8514

test:
  secret_key_base: 800fe6a4891ce9b827ac353885a3c1bca4857aaad9d6b61c6c14c8fba9ac227ab5049bcbc83e9a6ef3f96db932d76a578419e78d7788e4269e8ce2a25945714f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
